cache:
  paths:
    - node_modules/

build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - yarn

lint-job1:
  stage: test
  script:
    - yarn lint

test-job:
  stage: test
  script:
    - echo "This job tests something"