stages:
  - build
  - check-lint
  - test

cache:
  paths:
    - node_modules/

build-job:
  stage: build
  script:
    - yarn

lint-job:
  stage: check-lint
  script:
    - yarn lint

test-job:
  stage: test
  script:
    - yarn test