stages:
  - sync-git
  - build
  - check-lint
  - test

cache:
  paths:
    - node_modules/

sync:
  stage: sync-git
  script: 
    - git remote remove github
    - git remote add github https://{$GITHUB_COM_USER}:{GITHUB_PASSWORD}@github.com/BryakunovIvan/password-manager-client.git
    - git push --all github
